### PR TITLE
ARROW-10647: Add in Rust performance testing file

### PR DESCRIPTION
**Pull request by alamb**
We are adding a rust performance benchmark to the arrow repo, in https://github.com/apache/arrow/pull/8708

In order to avoid adding 653K of binary data to that repo, @sunchao  suggested adding it here

### CODE REVIEW

**Comment by alamb** [comment]
I am not sure how to request a review on this PR (github does not seem to want to let me do so). FYI @wesm

**Comment by wesm** [comment]
Hm. Is there a plan for "endogenous" performance testing (creating test files on the fly)?

**Comment by wesm** [comment]
(you have to be a "Parquet" committer to be able to merge patches here or request reviews)

**Comment by alamb** [comment]
@wesm 
> Hm. Is there a plan for "endogenous" performance testing (creating test files on the fly)?

Not that I am aware of. Given what these files are being used for, I don't see any reason we can't generate them on the fly. I'll work with @sunchao  on that.

**Pull request closed without merging**
