### PR TITLE
Add 10k-v2 and stock_simulated for testing and benchmarking Rust library

### PR DESCRIPTION
**Pull request by alecmocatta**
In the import of the Rust parquet library from http://github.com/sunchao/parquet-rs, the benchmarks and their required files `10k-v2.parquet` and `stock_simulated.parquet` weren't copied across.

This adds them so that updated benchmarks can be included in https://github.com/apache/arrow/pull/3461.

### CODE REVIEW

**Comment by wesm** [comment]
These files are a bit big. Can you generate some data files using pyarrow or similar as part of the benchmarking process?

**Comment by alecmocatta** [comment]
Good idea. Is it possible though that the generated files could change as pyarrow changes over time? I'd like to ensure the files are bit-for-bit identical over time, for consistent benchmark results.

**Comment by wesm** [comment]
You could pin the pyarrow version used to generate them

**Comment by alecmocatta** [comment]
Thanks. I'm not familiar with how to do that but I'll take a look once the aforementioned PR is merged. I removed the benchmarks from it so this PR isn't needed immediately.

**Comment by wesm** [comment]
I have a lot on my plate. @andygrove or @sunchao could you take ownership of this? I don't like the idea of checking 1MB files into source control, particularly for benchmarking, so please don't do that without checking with me first

**Comment by andygrove** [comment]
I'm happy to take this on. I am in the final week of a release in my day
job so may not have much time until this weekend.

**Comment by andygrove** [comment]
I'm about to embark on some benchmarking with large files too so I face similar challenges.

Generating test data as part of the build seems like the way to go in order to catch performance regressions in the core libraries. 

I am also maintaining my own repo where I have benchmarks against popular public data sets (and I'm just relying on wget or curl to download them).

**Pull request closed without merging**
