### PR TITLE
ARROW-11452: Add file for testing ARROW-11452

### PR DESCRIPTION
**Pull request by maxburke**

### CODE REVIEW

**Comment by maxburke** [comment]
@pitrou Would it be possible to get this merged?

**Comment by nevi-me** [comment]
@maxburke I hadn't seen that you added this. I'll open a PR against your fork, wanted to use a less generic name, and document why we are adding the file.

**Comment by wesm** [comment]
I can merge this if it's ready to go in

**Comment by nevi-me** [comment]
@wesm yes please

**Pull request merged**
