### PR TITLE
Add empty file with list data

### PR DESCRIPTION
**Pull request by novemberkilo**
Please see https://github.com/apache/arrow-rs/pull/1448#discussion_r828219982 for context

### CODE REVIEW

**Review by sunchao — APPROVED** [review]
+1

**Comment by sunchao** [comment]
cc @pitrou

**Review by viirya — APPROVED** [review]

**Comment by pitrou** [comment]
Can you please add a line describing the file here: https://github.com/apache/parquet-testing/blob/master/data/README.md?

**Comment by pitrou** [comment]
Also, it would be nice if this was paired with a JIRA ticket at https://issues.apache.org/jira/projects/PARQUET/

**Comment by novemberkilo** [comment]
@pitrou thanks for reviewing - I've added a description.

**Review by nevi-me — APPROVED** [review]

**Pull request merged**
