### PR TITLE
ARROW-18420: [Parquet] Add fixed_length_byte_array.parquet for page index test

### PR DESCRIPTION
**Pull request by wgtmac**
This patch adds a parquet file generated by parquet-mr with following attributes:
- a single column with fixed_length_byte_array type of size 4.
- values are ordered in the descending order.
- in total 1000 values written into 10 pages, with some random null values.
- page index is generated.

After this file has been committed, I can go ahead to finish test cases required for page index in the https://github.com/apache/arrow/pull/14803

Below is the complete java code to generate the file:
```java
package org.apache.parquet.cli.commands;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.parquet.column.ParquetProperties;
import org.apache.parquet.example.data.Group;
import org.apache.parquet.example.data.simple.SimpleGroupFactory;
import org.apache.parquet.hadoop.ParquetWriter;
import org.apache.parquet.hadoop.example.GroupWriteSupport;
import org.apache.parquet.hadoop.metadata.CompressionCodecName;
import org.apache.parquet.io.api.Binary;
import org.apache.parquet.schema.MessageType;
import org.apache.parquet.schema.PrimitiveType;
import org.apache.parquet.schema.Types;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.Random;

public class GenerateTestFile {

  public static void main(String[] args) {
    Path path = new Path("/tmp/fixed_length_byte_array.parquet");
    Configuration conf = new Configuration();

    MessageType schema = Types.buildMessage()
      .required(PrimitiveType.PrimitiveTypeName.FIXED_LEN_BYTE_ARRAY).length(4)
      .named("flba_field")
      .named("schema");
    SimpleGroupFactory fact = new SimpleGroupFactory(schema);
    GroupWriteSupport.setSchema(schema, conf);

    try (
      ParquetWriter<Group> writer = new ParquetWriter<>(
        path,
        new GroupWriteSupport(),
        CompressionCodecName.UNCOMPRESSED,
        /*blockSize=*/1024 * 1024,
        /*pageSize=*/128,
        /*dictionaryPageSize=*/128,
        /*enableDictionary=*/false,
        /*validating=*/false,
        ParquetProperties.WriterVersion.PARQUET_1_0,
        conf)) {

      Random rnd = new Random();
      for (int i = 1000; i > 0; --i) {
        if (rnd.nextInt(10) == 5) {
          writer.write(fact.newGroup());
        } else {
          ByteBuffer buffer = ByteBuffer.allocate(Integer.BYTES);
          writer.write(fact.newGroup()
            .append("flba_field",
              Binary.fromConstantByteArray(buffer.putInt(0, i).array())));
        }
      }
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

}
```

### CODE REVIEW

**Comment by wgtmac** [comment]
@pitrou @emkornfield Can you please take a look? Thanks!

**Review by pitrou — APPROVED** [review]
Nice, thank you!

**Comment by ccleva** [comment]
@wgtmac @pitrou sorry for coming back on this. The generated file has null values in a required field. This causes an EOFException when one tries to read it using the hadoop parquet reader and the equivalent error with pyArrow.
https://github.com/apache/parquet-java/issues/3336
https://github.com/apache/arrow/issues/47662
Is it something that should be fixed? Making the field optional solves the issue with both readers.

**Comment by pitrou** [comment]
> Is it something that should be fixed? Making the field optional solves the issue with both readers.

Oh, yes, definitely, thanks for spotting this. Do you want to submit a PR fixing the file?

**Comment by ccleva** [comment]
Sure, I will do that

**Pull request merged**
