### PR TITLE
PARQUET-2187: Update rle_boolean_encoding file with more rows

### PR DESCRIPTION
**Pull request by sfc-gh-nthimmegowda**
Jira link : https://issues.apache.org/jira/projects/PARQUET/issues/PARQUET-2187

The previous file with RLE encoding with boolean type had only 7 rows, which did not use `rle-run` part of the encoded data

RLE encoding has a combination of` <bit-packed-run>` and ` <rle-run>` . [RLE encoding ](https://parquet.apache.org/docs/file-format/data-pages/encodings/#a-namerlearun-length-encoding--bit-packing-hybrid-rle--3)

`run := <bit-packed-run> | <rle-run>`

Replacing with a new file with more data (68 rows) , produced by the following statement. This ensures we will have coverage for both `bit-packed` decoding and `rle-run` decoding

Create with Athena. 

insert into  boolean_datatype_athena VALUES (true), (false), (null), (true), (true), (false), (false), (true) ,  (true), (true), (false), (false), (true),
 (true), (false), (null), (true), (true), (false), (false), (true) , (true), (false), (null), (true), (true), (false), (false), (true) ,  (true), (true), (false), (false) , (false), (false), (true) , (true), (false), (null), (true), (true), (false), (false), (true) ,  (true), (true), (false), (false), (null), (true), (true), (false), (false), (true) ,  (true), (true) ,(false), (true) , (true), (false), (null), (true), (true), (false), (false), (true) ,  (true), (true)  ;

### CODE REVIEW

**Comment by sfc-gh-nthimmegowda** [comment]
@sunchao @nevi-me @pitrou @wesm . Sorry for the repeat.  Could any of you please review? 

This was raised by @kou in 
https://github.com/apache/arrow/pull/14147 for Parquet-cpp as part of review.

**Comment by pitrou** [comment]
@achille-roussel could you take a look at this file?

**Comment by achille-roussel** [comment]
The file seems compatible with https://github.com/segmentio/parquet-go 👍

**Comment by pitrou** [comment]
Thank you @sfc-gh-nthimmegowda @achille-roussel

**Pull request merged**
