### PR TITLE
ARROW-6687: Add .parquet file with single np.nan value

### PR DESCRIPTION
**Pull request by alippai**
Testing the new DataFusion .parquet support discovered an error. Adding a simple regression test resource to test it

### CODE REVIEW

**Comment by andygrove** [comment]
@wesm could you merge this please

**Comment by wesm** [comment]
I'm worried about going down this route as a testing approach. Do you plan to keep adding more files as you develop the Parquet Rust project?

**Comment by andygrove** [comment]
Yes, we definitely need more parquet files to test against. The current testing is very limited.

Is you concern about checking in static files versus generating them using them scripts?

**Comment by wesm** [comment]
Yes, I don't think that having a static corpus is a scalable testing strategy.

**Comment by andygrove** [comment]
I hear you. On the other hand, if the Rust developers now have to have a C++ and/or Python env set up as well to be able to run tests, that's also not ideal either. I suppose this could be Dockerized though?

**Comment by wesm** [comment]
The ideal scenario is to generate files endogenously using the Rust library and not relying on a different project. That's what we do in C++ (and what the Java library does also). I think checking in "problem" files that exhibit issues that you cannot easily generate from a particular library is okay.

**Comment by wesm** [comment]
Once Rust has a fully capable IPC implementation I'd be supportive of developing some Dockerized automated fuzz/integration testing between the C++/Python/R and Rust libraries. We can have the libraries cross-validate Parquet versus the Arrow protocol "point of truth"

**Comment by andygrove** [comment]
> The ideal scenario is to generate files endogenously using the Rust library 

Unfortunately the Rust implementation doesn't yet have support for writing Parquet files.

**Comment by wesm** [comment]
Okay. I think it's very important for the Rust developers to prioritize this otherwise it will be very difficult for the project to mature into something that people can depend on in production.

**Comment by wesm** [comment]
Merging this. 

Short of writing Parquet files from Rust if this becomes a pattern I would recommend writing a data generation script in Python and providing a Dockerfile to run it as part of the testing process

**Pull request merged**
