### PR TITLE
PARQUET-2187: Add Test parquet file RLE encoding with boolean columns

### PR DESCRIPTION
**Pull request by sfc-gh-nthimmegowda**
PARQUET-2187

* Test file for RLE decoding
* Update README

Created with Athena. 
insert into  boolean_datatype_athena VALUES (true), (false), (null), (true), (true), (false), (false), (true) ;

Jira link : https://issues.apache.org/jira/projects/PARQUET/issues/PARQUET-2187

### CODE REVIEW

**Comment by sfc-gh-nthimmegowda** [comment]
@sunchao @nevi-me @pitrou @wesm Could any of you please review?

**Comment by pitrou** [comment]
@sfc-gh-nthimmegowda Thanks for the PR. Is there any other implementation than Athena that is able to read this file?

**Comment by sfc-gh-nthimmegowda** [comment]
> @sfc-gh-nthimmegowda Thanks for the PR. Is there any other implementation than Athena that is able to read this file?

@pitrou . Apart from Athena, Spark and Trino can read this file (All parquet-mr / Java based implementations can). Paquet-cpp (c++) based implementation cannot. I have a fix for paquet-cpp which I plan to merge next with tests designed to validate access on this file.

**Comment by pitrou** [comment]
@sfc-gh-nthimmegowda I see, thanks. +1, will merge.

**Comment by pitrou** [comment]
@sfc-gh-nthimmegowda Is there a JIRA associated with this PR?

**Comment by sfc-gh-nthimmegowda** [comment]
> @sfc-gh-nthimmegowda Is there a JIRA associated with this PR?

Ack. Updated title and description with JIRA link

**Comment by achille-roussel** [comment]
Hello @sfc-gh-nthimmegowda, @pitrou,

It appears that the file introduced by this pull request is diverging from the parquet specification. The page contains a non-empty repetition level despite the column being neither repeated nor nested within a repeated parent column.

```
$ parquet-tools schema rle_boolean_encoding.parquet
message table {
  optional boolean datatype_boolean = 1;
}
```

This is the content of the data page header (notice the 1 byte repetition level length):
```
{NumValues:8 NumNulls:1 NumRows:8 Encoding:RLE DefinitionLevelsByteLength:2 RepetitionLevelsByteLength:1 IsCompressed:<nil> Statistics:{Max:[] Min:[] NullCount:0 DistinctCount:0 MaxValue:[] MinValue:[]}}
```

The one byte of the repetition level has value 0x10 at offset 21 (after the page header):
```
00000000  15 06 15 12 15 3a 5c 15  10 15 02 15 10 15 06 15  |.....:\.........|
00000010  04 15 02 00 00 10 03 fb  1f 8b 08 00 00 00 00 00  |................|
00000020  00 00 63 62 60 60 60 f6  05 00 46 6e 4a df 06 00  |..cb```...FnJ...|
00000030  00 00                                             |..|
```

* [0x03, 0xfb] is the definition level
* [0x1f, 0x8b] is the magic number at the beginning of the gzip header for the compressed page values

According to the parquet specification, the repetition level should not be encoded in this case:

> The encoded values for the data page is always required. The definition and repetition levels are optional, based on the schema definition. If the column is not nested (i.e. the path to the column has length 1), we do not encode the repetition levels (it would always have the value 1). For data that is required, the definition levels are skipped (if encoded, it will always have the value of the max definition level).

Since the Java and C++ parquet libraries appear to accept this file, should the parquet format spec be updated to document the fact that non-empty repetition levels should be skipped when the column isn't repeated?

**Comment by sfc-gh-nthimmegowda** [comment]
> Hello @sfc-gh-nthimmegowda, @pitrou,
> 
> It appears that the file introduced by this pull request is diverging from the parquet specification. The page contains a non-empty repetition level despite the column being neither repeated nor nested within a repeated parent column.
> 
> ```
> $ parquet-tools schema rle_boolean_encoding.parquet
> message table {
>   optional boolean datatype_boolean = 1;
> }
> ```
> 
> This is the content of the data page header (notice the 1 byte repetition level length):
> 
> ```
> {NumValues:8 NumNulls:1 NumRows:8 Encoding:RLE DefinitionLevelsByteLength:2 RepetitionLevelsByteLength:1 IsCompressed:<nil> Statistics:{Max:[] Min:[] NullCount:0 DistinctCount:0 MaxValue:[] MinValue:[]}}
> ```
> 
> The one byte of the repetition level has value 0x10 at offset 21 (after the page header):
> 
> ```
> 00000000  15 06 15 12 15 3a 5c 15  10 15 02 15 10 15 06 15  |.....:\.........|
> 00000010  04 15 02 00 00 10 03 fb  1f 8b 08 00 00 00 00 00  |................|
> 00000020  00 00 63 62 60 60 60 f6  05 00 46 6e 4a df 06 00  |..cb```...FnJ...|
> 00000030  00 00                                             |..|
> ```
> 
> * [0x03, 0xfb] is the definition level
> * [0x1f, 0x8b] is the magic number at the beginning of the gzip header for the compressed page values
> 
> According to the parquet specification, the repetition level should not be encoded in this case:
> 
> > The encoded values for the data page is always required. The definition and repetition levels are optional, based on the schema definition. If the column is not nested (i.e. the path to the column has length 1), we do not encode the repetition levels (it would always have the value 1). For data that is required, the definition levels are skipped (if encoded, it will always have the value of the max definition level).
> 
> Since the Java and C++ parquet libraries appear to accept this file, should the parquet format spec be updated to document the fact that non-empty repetition levels should be skipped when the column isn't repeated?

I think we should the spec should be changed only with respect to, what data is written and not how it should be read. The issue is here repetition got encoded even though the column attributes were not supported. If we are going with solidifying changes, we should aim to conrectize that encoded values should not repetition value for the columns you described.

**Pull request merged**
