### PR TITLE
adding some bad parquet files

### PR DESCRIPTION
**Pull request by jp0317**
Hi, these two bad files can help reproduce the two examples mentioned in https://github.com/apache/arrow-rs/issues/6228.

### CODE REVIEW

**Comment by mapleFU** [comment]
Just wonder how these file is generated? 🤔 Seems we have some "little" file here

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
@jp0317 I've check the bad-dict file, it throw here in C++ code:

```
  if (col_start < 0 || col_length < 0) {
    throw ParquetException("Invalid column metadata (corrupt file?)");
  }

  if (AddWithOverflow(col_start, col_length, &col_end) || col_end > source_size) {
    throw ParquetException("Invalid column metadata (corrupt file?)");
  }
```

So maybe arrow-rs can also check this? ( also cc @alamb )

**Comment by mapleFU** [comment]
@pitrou Would you mind check the naming of the 2 new bad file here?

**Review by pitrou — APPROVED** [review]

**Comment by alamb** [comment]
> So maybe arrow-rs can also check this? ( also cc @alamb )

I agree we should add tests to parquet-rs to test these bad files. I'll see what i can do

**Comment by alamb** [comment]
> So maybe arrow-rs can also check this? ( also cc @alamb )

I made a PR to check these files with Rust: https://github.com/apache/arrow-rs/pull/6262

**Comment by jp0317** [comment]
> @jp0317 I've check the bad-dict file, it throw here in C++ code:
> 
> ```
>   if (col_start < 0 || col_length < 0) {
>     throw ParquetException("Invalid column metadata (corrupt file?)");
>   }
> 
>   if (AddWithOverflow(col_start, col_length, &col_end) || col_end > source_size) {
>     throw ParquetException("Invalid column metadata (corrupt file?)");
>   }
> ```
> 
> So maybe arrow-rs can also check this? ( also cc @alamb )

yes, iiuc we can first improve type conversions as mentioned https://github.com/apache/arrow-rs/issues/6228. For this particular case the lenth is negative but currently our rust codes just convert them as unsigned integers directly.

**Comment by mapleFU** [comment]
I've an issue here: https://github.com/apache/arrow-rs/issues/6255 , glad to learn some rust code lol

**Pull request merged**
