### PR TITLE
PARQUET-1998: Add LZ4_RAW compressed files

### PR DESCRIPTION
**Pull request by pitrou**
The files were generated with Parquet C++.

* `lz4_raw_compressed.parquet` contains the same data as `hadoop_lz4_compressed.parquet`.
* `lz4_raw_compressed_larger.parquet` contains the same data as `hadoop_lz4_compressed_larger.parquet`.

Here are the file contents for `lz4_raw_compressed.parquet`:
```
File Name: parquet-testing/data/lz4_raw_compressed.parquet
Version: 1.0
Created By: parquet-cpp version 1.5.1-SNAPSHOT
Total rows: 4
Number of RowGroups: 1
Number of Real Columns: 3
Number of Columns: 3
Number of Selected Columns: 3
Column 0: c0 (INT64)
Column 1: c1 (BYTE_ARRAY)
Column 2: v11 (DOUBLE)
--- Row Group: 0 ---
--- Total Bytes: 251 ---
--- Total Compressed Bytes: 238 ---
--- Rows: 4 ---
Column 0
  Values: 4, Null Values: 0, Distinct Values: 0
  Max: 1593604801, Min: 1593604800
  Compression: LZ4_RAW, Encodings: PLAIN RLE
  Uncompressed Size: 93, Compressed Size: 85
Column 1
  Values: 4, Null Values: 0, Distinct Values: 0
  Max: def, Min: abc
  Compression: LZ4_RAW, Encodings: PLAIN RLE
  Uncompressed Size: 59, Compressed Size: 58
Column 2
  Values: 4, Null Values: 0, Distinct Values: 0
  Max: 42.125, Min: 7.7
  Compression: LZ4_RAW, Encodings: PLAIN RLE
  Uncompressed Size: 99, Compressed Size: 95
--- Values ---
c0                            |c1                            |v11                           |
1593604800                    |abc                           |42.000000                     |
1593604800                    |def                           |7.700000                      |
1593604801                    |abc                           |42.125000                     |
1593604801                    |def                           |7.700000                      |
```

Here are the partial file contents for `lz4_raw_compressed_larger.parquet`:
```
File Name: parquet-testing/data/lz4_raw_compressed_larger.parquet
Version: 1.0
Created By: parquet-cpp version 1.5.1-SNAPSHOT
Total rows: 10000
Number of RowGroups: 1
Number of Real Columns: 1
Number of Columns: 1
Number of Selected Columns: 1
Column 0: a (BYTE_ARRAY/UTF8)
--- Row Group: 0 ---
--- Total Bytes: 400103 ---
--- Total Compressed Bytes: 380480 ---
--- Rows: 10000 ---
Column 0
  Values: 10000, Null Values: 0, Distinct Values: 0
  Max: ffffe6a0-e0c0-4e65-a9d4-f7f4c176aea2, Min: 00087de7-10df-4979-94cf-79279f9745ce
  Compression: LZ4_RAW, Encodings: PLAIN RLE
  Uncompressed Size: 400103, Compressed Size: 380480
--- Values ---
a                             |
c7ce6bef-d5b0-4863-b199-8ea8c7fb117b|
e8fb9197-cb9f-4118-b67f-fbfa65f61843|
885136e1-0aa1-4fdb-8847-63d87b07c205|
ce7b2019-8ebe-4906-a74d-0afa2409e5df|
a9ee2527-821b-4b71-a926-03f73c3fc8b7|
[...]
```

### CODE REVIEW

**Comment by emkornfield** [comment]
I think in the past some of the problems have been to compression over larger blocks?  It might pay to add more values, otherwise LGTM.

**Comment by pitrou** [comment]
We may want to add a separate larger file, then. It's useful to have a small file for easier debugging.

**Comment by emkornfield** [comment]
SGTM.

**Comment by gszadovszky** [comment]
@pitrou, It is a good idea to have this file in parquet-testing. It'll help a lot for testing parquet-mr's implementation of LZ4_RAW. But please keep in mind that until we don't release parquet-format with this new encoding we shall not release any implementation of it.

**Comment by pitrou** [comment]
@gszadovszky What the results for releasing a new version of parquet-format?

**Comment by gszadovszky** [comment]
See [How to release](http://parquet.apache.org/documentation/how-to-release/) for details but practically it is not a big deal. The issue is (at least for parquet-mr) we don't have too many active PMC members and we require three +1 votes from them (us). Another thing is we should advertise a parquet-format release vote for a broader audience and not only on the parquet dev list. The issue is there might be a couple of parquet implementation that are not part of the apache parquet community.
There are also a couple of ongoing PRs but if you think the this change is urgent enough to not wait for them I am OK with it. 

Currently, the 1.12.0 parquet-mr release is ongoing. It is not a blocker of a parquet-format release but might be confusing to start another releasing on the dev list at the same time.

**Comment by pitrou** [comment]
I don't think it's urgent, also I'll add a larger file in this PR as suggested by @emkornfield .

**Comment by pitrou** [comment]
Updated with a larger file as well.

**Comment by pitrou** [comment]
I think I'm going to merge this. Please speak up if you want to object :-)

**Comment by emkornfield** [comment]
I think we wanted to hold off until a release of the spec?

**Comment by pitrou** [comment]
I may have misunderstood @gszadovszky , but it seems to me the barrier is on release an implementation (such as Parquet C++) with support for the new codec. Adding files to `parquet-testing` should be fine?

**Comment by gszadovszky** [comment]
@pitrou, I think the issue is that these files are created by an un-released parquet-cpp. It has a risk that these files would have never be written by a released parquet-cpp as is because of some modifications to be added later.
Meanwhile I am fine having these files in the test repo if they will be re-visited after a parquet-cpp release.

**Comment by pitrou** [comment]
That is a legitimate concern, and someone working on the Java implementation can temporarily grab the files from this PR. @emkornfield What do you think?

**Comment by pitrou** [comment]
I think I'm going to merge this so that integration testing can be wired in https://github.com/apache/arrow/pull/9782
I can re-emit the files later with a released version of parquet-cpp.

**Pull request merged**
