### PR TITLE
Add parquet file with optional metadata

### PR DESCRIPTION
**Pull request by shanisolomon**
Add parquet file with optional metadata: bloom filters, encoding stats, column index and offset index.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @shanisolomon  -- I think this type of file would be valuable to have in the repository, though given it is fairly large (2MB) that may be a problem as this repo is checked out in many many CI jobs across the different implementations. 

Can you perhaps explain how it was created in https://github.com/apache/parquet-testing/blob/master/data/README.md?

@pitrou  do you know of / have any suggestions for example parquet files in this repo that have bloom filters, column index and offset index in their metadata?

**Comment by pitrou** [comment]
> @pitrou do you know of / have any suggestions for example parquet files in this repo that have bloom filters, column index and offset index in their metadata?

No, unfortunately. I think you'll have to examine individual files to see if one of them fits the bill.

**Comment by alamb** [comment]
> No, unfortunately. I think you'll have to examine individual files to see if one of them fits the bill.

Thanks -- I'll poke around and post what I find

**Comment by shanisolomon** [comment]
@alamb I've already browsed within the tests files under the `data` folder and couldn't find ones with these optional metadata.

I can provide a 1 MB file instead, but as for this [issue ](https://issues.apache.org/jira/browse/PARQUET-2122) it seems like there's a issue of bloating parquet file size once adding bloom filters are added, so we can add an action item to replace the file once its resolved.

**Comment by alamb** [comment]
Thanks @shanisolomon  a smaller file would be great - I think the smaller this file can be the better (especially if the idea is not to actually read from the file but to read its metadata).

**Comment by shanisolomon** [comment]
@alamb done :)

**Review by alamb — APPROVED** [review]
Looks good to me @shanisolomon  

```shell
(arrow_dev) alamb@MacBook-Pro-2:~/Software/parquet-testing$ parquet-tools meta data/data_index_bloom_encoding_stats.parquet 
gifile:        file:/Users/alamb/Software/parquet-testing/data/data_index_bloom_encoding_stats.parquet 
creator:     parquet-mr version 1.13.0-SNAPSHOT (build 7398d9b522733c669d497c25495c9efa1c860994) 
extra:       parquet.avro.schema = {"type":"record","name":"data","fields":[{"name":"String","type":["null","string"],"doc":"Type inferred from 'Hello'","default":null}]} 
extra:       writer.model.name = avro 

file schema: data 
--------------------------------------------------------------------------------
String:      OPTIONAL BINARY L:STRING R:0 D:1

row group 1: RC:14 TS:163 OFFSET:4 
--------------------------------------------------------------------------------
String:       BINARY GZIP DO:0 FPO:4 SZ:152/163/1.07 VC:14 ENC:RLE,PLAIN,BIT_PACKED ST:[min: Hello, max: today, num_nulls: 0]
```

```shell
(arrow_dev) alamb@MacBook-Pro-2:~/Software/parquet-testing$ ls -ltr data/data_index_bloom_encoding_stats.parquet 
-rw-r--r--  1 alamb  staff   1.6K Feb 15 08:34 data/data_index_bloom_encoding_stats.parquet
```

Thank you @zeevm and @shanisolomon

**Comment by alamb** [comment]
@pitrou  would it be possible to merge this PR? I do not have access to do so: 
Screen Shot 2022-02-15 at 8 42 19 AM

**Comment by pitrou** [comment]
@alamb Done!

**Comment by alamb** [comment]
Thank you @pitrou

**Pull request merged**
