### PR TITLE
PARQUET-1621: [C++] Add encrypted parquet files to apache parquet-testing repository

### PR DESCRIPTION
**Pull request by revit1976**

### CODE REVIEW

**Comment by wesm** [comment]
Should there be keys to go with these files?

**Comment by ggershinsky** [comment]
> Should there be keys to go with these files?

Looks like there are two options:
- add the keys, with some explanation, to the https://github.com/apache/parquet-testing/blob/master/data/README.md file (or similar)
- in this md file, add a pointer to the decryption tester (currently [here](https://github.com/revit1976/arrow/blob/new_tests/cpp/src/parquet/encryption-read-configurations-test.cc), being added to the main pull request).  This tester file has all encryption keys, with their names, with aadPrefixes (file ids) where needed, with data verification, with explanation, etc.

We'll go with the option that makes better sense to you.

**Comment by ggershinsky** [comment]
@wesm We've done both - added the keys and a link to the reader sample that decrypts these files.
Please merge this PR - the reader sample in the Arrow repo encryption PR depends on it.

**Comment by wesm** [comment]
OK, thanks. Merging now

**Pull request merged**
